### ISSUE TITLE
I recommend updating nodeactyl-v1-support to latest version i because of fixed bugs wich could cause errors

### ISSUE THREAD

**Issue by EiskalterFreund** [Linux123123/Pterodactyl-Discord-Bot#1]
I would recommend to update nodeactyl-v1-support to latest version because i fixed some realy error causing bugs

**Comment by Linux123123** [comment]
Thanks for telling! Will do.
Also thanks for working on supporting pterodactyl v1 for nodeactyl. You are great.

**Comment by EiskalterFreund** [comment]
nü
