### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ririko5834** [Linux123123/Pterodactyl-Discord-Bot#1]
Hello, can you pleaseadd these features:

- [ ] Command for admins to register and unregister users
- [ ] Command for admins to create server for user
- [x] Command for admins to get list of all users
- [x] Option to make live status embed of pterodactyl nodes (Edit the embed in specific  channel every 5 min with actual informations about nodes)

**Comment by Linux123123** [comment]
Right now I am at the phase of converting this project to typescript, but I will surely add those features later!

**Comment by Linux123123** [comment]
> * [x]  Option to make live status embed of pterodactyl nodes (Edit the embed in specific  channel every 5 min with actual informations about nodes)

What do you exactly mean here? The API doesn't let you to get the entire node CPU or memory usage only the servers can do that. And adding it all and diving would be kinda slow. Of course if there aren't thousands of servers add all the server CPU usage and diving by server count would be possible. The things that I can show easily are how many servers there are, how many allocations. Basically everything [here](https://jspteroapidocs.linux123123.cf/interfaces/applicationnode.nodeattributes.html) including the [relathionships](https://jspteroapidocs.linux123123.cf/interfaces/applicationnode.noderelationships.html).

**Comment by snaildos** [comment]
Like a status system. ^^

**Comment by Spexzzz** [comment]
i did `npm start` but the output is just an error and does not start. Says it cant fine /dist/index.js

**Comment by Linux123123** [comment]
Not related to this issue, but you first need to build with `npm build`.

**Comment by mrshadow-in** [comment]
i am using manual installinsation where to  put the tokens and api's

**Comment by Linux123123** [comment]
This project is now archived.
