### ISSUE TITLE
You do not have permission to use this command

### ISSUE THREAD

**Issue by skerit** [Linux123123/Pterodactyl-Discord-Bot#2]
I got the bot up and running, but I can't even do `!help`:

```
You do not have permission to use this command.
​Your permission level is 4 (Server Owner)
​This command requires level 0 (User)
```

I don't really know how to solve this

**Comment by Linux123123** [comment]
Sorry to hear. I might have an idea why this is happening. I will push a bug fix commit. You will just need to do `git pull`.

**Comment by Linux123123** [comment]
Assuming fixed. Closing. Open if issue persists.
