### ISSUE TITLE
How to add/change role 

### ISSUE THREAD

**Issue by thomasbonsirven** [Linux123123/Pterodactyl-Discord-Bot#4]
Hello,

I dont understand how to change my role.
For the moment i'm user role.
But i want change this.
How to ?

**Comment by Linux123123** [comment]
The server owner is automatically assigned the highest role. Then the server owner can add other roles to be used.

**Comment by thomasbonsirven** [comment]
Mmm, ok but how to owner can add me to Administrator ?
Whats is the correct command ?

Thanks in adavnce :)

**Comment by Linux123123** [comment]
So first the server admin creates a role.

Then when the role is created they run `!set edit adminRole <rolename>`

And then if you have that role when you run `!mylevel` it should say that you are Administrator.

**Comment by thomasbonsirven** [comment]
Hello,

Sorry, but with your command the owner change by administrator ( adminrole choose)

But its not resolve my problem.

the owner must put the administrator rights to another user.  How to ???

**Comment by Linux123123** [comment]
I already told exactly how to do that. There is no other way.

**Comment by thomasbonsirven** [comment]
Ok i understand.. but not work for me. Dont change. 
I have a sucess message, not change if use !mylevel.
