### ISSUE TITLE
[Question] Config ?

### ISSUE THREAD

**Issue by TheDarthFather** [Linux123123/Pterodactyl-Discord-Bot#5]
Stupid question .. where is config.js ?

**Comment by Linux123123** [comment]
It is in ```src/config/config.ts```, then after you edit it you need to rebuild the bot.

A lot easier way for you to do this is to create a `.env` file and add
```
TOKEN="token"
PTERO_TOKEN="token"
PTERO_CLIENT_TOKEN="token"
PTERO_HOST="panel.example.com"
```

This way you won't need to rebuild.

**Comment by TheDarthFather** [comment]
Thank you!
